services:
  fastapi:
    build: ./fastapi
    command: bash -c "poetry install && poetry run uvicorn retailys.main:app --reload --host 0.0.0.0"
    ports:
       - 8000:8000
    volumes:
      - ./fastapi:/retailys

  redis:
    image: redis:7

  svelte:
    build: ./svelte
    ports:
      - 3000:3000
    volumes:
      - ./svelte:/retailys
    command: bash -c "npm install --also-dev && npm run dev -- --host --port 3000"
